SkyTerraHelp:
  hilfe:
    Message: ""
  skyterra:
    Message: ""
  shophilfe:
    Message: ""
  team:
    Message: ""
  skybox:
    Message: ""
  news:
    Message: ""
  vip:
    Message: ""
  spenden:
    Message: ""
  frage:
    Message: ""
  ip:
    Message: ""